### PR TITLE
formatted corpora

### PR DESCRIPTION
**Pull request by dev-sabbir**

### CODE REVIEW

**Comment by souravsingh** [comment]
LGTM

**Comment by dev-sabbir** [comment]
What is LGTM ? I don't  understand. @souravsingh

**Comment by souravsingh** [comment]
Looks good to me

**Comment by souravsingh** [comment]
I will need to get confirmation from @kylepjohnson before this can be merged.

**Comment by dev-sabbir** [comment]
Oh! I see. Glad to hear that.

Ok we will wait for the confirmation from @kylepjohnson

**Pull request merged**
